backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
publish_mode: editorial_workflow
 
media_folder: "Documentation~/images"
 
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "Documentation~" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Body", name: "body", widget: "markdown"}